name: control_flow_graph
description: A library for creating and manipulating control flow graphs and SSA form.
version: 1.1.0
homepage: https://github.com/ethanblake4/control_flow_graph
topics:
  - compiler
  - ssa
  - graph

environment:
  sdk: ^3.2.0

dependencies:
  more: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
